version: "2"
services:
  # mysql
  mysql:
    image: mysql:5.7.19
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/config/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./logs/mysql:/var/log/mysql
      - ./services/mysql/run/mysqld:/var/run/mysqld
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: luvvien
      MYSQL_DATABASE: luvvien
      MYSQL_USER: luvvien
      MYSQL_PASSWORD: luvvien

  # php-fpm
  php-fpm:
    image: luvvien/docker-php-fpm-composer:latest
    container_name: php-fpm
    volumes:
      - ./apps:/apps
      - ./services/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./services/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./services/mysql/run/mysqld:/var/run/mysqld
    restart: always
    working_dir: /apps

  # Redis 
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    container_name: redis
    # environment:
    #   REDIS_PASSWORD: "luvvien"
    command: redis-server --requirepass luvvien
    volumes:
      - ./services/redis/data:/data
    restart: always

  # nginx
  nginx:
    image: pagespeed/nginx-pagespeed
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - mysql
      - nginx
    depends_on:
      - php-fpm
      - mysql
      - redis
    volumes:
      - ./apps:/apps
      - ./services/nginx/config/conf.d:/etc/nginx/conf.d
      - ./services/nginx/config/cert:/etc/nginx/cert
      - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    restart: always