version: "2"
services:
  # mysql
  mysql:
    image: mysql:5.7.19
    container_name: weengine-mysql
    ports:
      - 3308:3306
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/config/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./logs/mysql:/var/log/mysql
      - ./services/mysql/run/mysqld:/var/run/mysqld
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: luvvien1314
      MYSQL_DATABASE: weengine
      MYSQL_USER: weengine
      MYSQL_PASSWORD: luvvien1314@me

  # php-fpm
  php-fpm:
    image: luvvien/docker-php-fpm-composer:latest
    container_name: weengine-php-fpm
    volumes:
      - ./apps:/apps
      - ./services/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./services/php/config/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./services/mysql/run/mysqld:/var/run/mysqld
    restart: always
    working_dir: /apps

  # nginx
  nginx:
    image: nginx:latest
    container_name: weengine-nginx
    ports:
      - 8086:80
      - 10443:443
    links:
      - mysql
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - ./apps:/apps
      - ./services/nginx/config/conf.d:/etc/nginx/conf.d:ro
      - ./services/nginx/config/cert:/etc/nginx/cert:ro
      - ./services/nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    restart: always